### ISSUE TITLE
Split default layout into standalone components

### ISSUE THREAD

**Issue by acidbiscuit** [0x4447-bootstrap/0x4447_bootstrap_dashboard#122]
Default layout has grown since project start and now contains logic for specific layout parts which can be abstracted into standalone components: Sidebar, Toolbar.

**Comment by davidgatti** [comment]
@acidbiscuit my expectation is that you'd do that. Because this is a boostrap project, that will be used in more complex application, so I want it to already be set in a way that is ready for big projects.
