### ISSUE TITLE
Updated Sk in DB for user data

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#127]
For the SK key, add `profile` to the user data that is related to his profile and not the app itself.

**Comment by acidbiscuit** [comment]
@davidgatti Where does it apply? We currently use amplify to store and update user data, not DynamoDB.

**Comment by davidgatti** [comment]
If you check the issue closely, it is assigned to me :)

**Comment by davidgatti** [comment]
Done, now we have 3 tables: app, profile, money.
