### ISSUE TITLE
Replace DDB Query with DDB Get

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#174]
When you check if the user was already created in the DDB, you have to replace the .query() with .get(). The query is a way to expensive opration.

**Comment by acidbiscuit** [comment]
@davidgatti Need your input to overcome DynamoDB ValidationException `The provided key element does not match the schema` when using `.get()`. I've tried various combinations of `Key` values: pk, sk, sub, email, none seem to work.
