### ISSUE TITLE
Issue with the User ID

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#175]
There is something wrong with the Cognito ID. As you can see from the screenshots here, in S3 we can see `us-east-1:6156d9c2-9a04-41f0-a9cc-3ddfd225449f`. And this is a wrong ID that you use when you save the avatar in S3. Where ass the other ID `us-east-1:cb652f7f-cfe6-4e47-bea6-fbf96d52e1b3` is the correct one. So the ID that lands in DDB when the user first log-in is correct, then the temporary avatar that I create for the user has the correct ID, and when we save the image from the dashboard we use the wrong ID despite the debug page shows the right one.

If you can't figure out this one within 1h, let me know, we can do something to make make debugging esier.

P.s After few days I did update the image, and now you did use the right ID, I think the Amplify SDK is storing things the wrong way, and it is not refreshing the ID correctly. Maybe you have to force it to get the fresh value? Not sure.

![Screen Shot 2021-02-10 at 11 17 50 AM](https://user-images.githubusercontent.com/411114/107496468-a655c180-6b91-11eb-9243-fd205efa9099.png)
![Screen Shot 2021-02-10 at 11 17 56 AM](https://user-images.githubusercontent.com/411114/107496474-a6ee5800-6b91-11eb-81ef-bafa139b496c.png)
![Screen Shot 2021-02-10 at 11 18 00 AM](https://user-images.githubusercontent.com/411114/107496476-a6ee5800-6b91-11eb-87f6-ce43a581c350.png)
![Screen Shot 2021-02-10 at 11 26 41 AM](https://user-images.githubusercontent.com/411114/107497432-dd78a280-6b92-11eb-9075-8ae5596d8e96.png)

**Comment by acidbiscuit** [comment]
@davidgatti Since it is not exactly clear on how to produce the issue, I will need your feedback on changes I've made.

Please, check this branch:
https://github.com/0x4447-bootstrap/0x4447_bootstrap_dashboard/tree/vv/%23175-use-aws-credentials-for-avatar

I'm now using AWS credentials instead of Amplify credentials for uploading and retrieving user avatar.
