### ISSUE TITLE
Invoice Pagination

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#178]
When you make a query, and get an empty array, you should disable the pagination for the next year. Right now you can paginate until infinity.

**Comment by acidbiscuit** [comment]
@davidgatti This is not possible with Vuetify table API and the way we are using the table. I've spent a bunch of time on it before, but it doesn't work with inconsistent (unlimited) items per page.

**Comment by davidgatti** [comment]
Let's go back to the basic. Pagination by 12 items at the time.

**Comment by acidbiscuit** [comment]
@davidgatti Please, ping me when you have an account with at least 4-5 invoices. Needed for testing.

**Comment by davidgatti** [comment]
I'm still thinking how to go about this.

**Comment by davidgatti** [comment]
OK, I came up with a solution for the pagination, now in DDB you get a new SK. If you do a getitem query you can check for this `stats#invoice#2021`, and in return you will get:

```
{
  "count": 8,
  "pk": "us-east-1:6fd791c7-192d-4d40-8025-e8a4f3b11753",
  "sk": "stats#invoice#2021"
}
```
This wya you will know exactly how many invoices are in one year. If you do a query in DDB with the option of startswith() `stats#invoice#`, then you will get all the years there are invoices in the system.

Let me know if you need help with the queries, or would like a quick chat.
