### ISSUE TITLE
Standardize the gap between blocks

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#187]
Would it be possible to also standardize the gap between blocks?

![Screen Shot 2021-02-10 at 11 55 43 AM](https://user-images.githubusercontent.com/411114/107500969-14e94e00-6b97-11eb-8020-109fa919bf57.png)

**Comment by acidbiscuit** [comment]
@davidgatti There is no need to standartize the gap since it comes symmetric from Vuetify. I've made a mistake in markup that resulted in unequal gap between cards. Fixed in #204
