### ISSUE TITLE
Save the Support message in the S3 bucket

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#191]
I have this S3 bucket `0x4447-support-web-messages`, and we need to save the support message in to this bucket i nthe following way:

```
{
    "subject": "Subject",
    "body": "Body of the email",
    "emails": {
        "to": {
            "name": "First and last name"
            "email": "name@example.com"
        },
        "reply_to": {
            "name": "First and last name",
            "email": "name@example.com"
        }
    },
    "icalEvent": "Optional",
    "attachments": [ 
        {
            "filename": "OPTIONAL.pdf",
            "content": "A_BUFFER.toString('base64')",
            "encoding": "base64"
        }
    ]
}
```

With the following path: `0x4447-support-web-messages/USER_ID/RANDOM_UUID`

IMPORTANT: this bucket is in a different AWS account, I think I set the policy correctly to allow you to access it, but I never did this so I'm not sure, this might not work, so if you get an error, copy and paste it here.

**Comment by acidbiscuit** [comment]
@davidgatti Should we implement support message save with example data above or we should adjust support form to match the data? We currently don't have all necessary fields to match example above.

**Comment by davidgatti** [comment]
- subject: `Support request from: DOMAIN_NAME`
- Body: concatenate the two text areas
- email to: keep example
- reply_to: logged in user
- ical: no
- attachements: yes, once the issue is done :)

**Comment by acidbiscuit** [comment]
@davidgatti I've added a PR, but there is CORS issue during upload. I am not sure if all settings are correct.

**Comment by davidgatti** [comment]
If corse then my problem, will fix it :)
