### ISSUE TITLE
Add cash expiration when uploading to S3

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#208]
When uploading avatars, add a tag for cash expiration 365 days in the future.

**Comment by acidbiscuit** [comment]
@davidgatti I've mistakenly pushed changed to master branch. [Commit](https://github.com/0x4447-bootstrap/0x4447_bootstrap_dashboard/commit/4325a7069f0d68f9dd0b9e562a7bb760820be220)
