### ISSUE TITLE
Make subscription check example

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#215]
Make a button that when clicked will invoke the lambda that returns if the subscription is valid or not, and based on that show a modal if the subscription is missing.

**Comment by acidbiscuit** [comment]
@davidgatti Where should we place such button?

**Comment by davidgatti** [comment]
Since this is paused, this issues are missing, once I'll resume I'll update the issue.

**Comment by davidgatti** [comment]
There is a new lambda for you called `dashboard_app_subscription_check` that accpets the following payload:

```
{
    "cognito_id": "us-east-1:6fd791c7-192d-4d40-8025-e8a4f3b11753"
}
```

And spits out the following result

```
{
    "is_subscribed": false
}
```

The idea is to add on the home page a button, with the text `Save` and when you click it, you invoke this lambda, pass the user ID, and if you get if you can "save" the data in DDB. If you get back a false, you should show a modal that explains that to save data you have to subscribe to a plan, with the cancel button, and the other to go to the payment page. 

And now that I write this, I'm thinking that maybe I should go about this a bitt differently becasue anyone could go pass this check from the browser. So maybe we should pass the data to a lambda, but this is something I have to think about, regardless. the flow will be this one, with the difference that the name of the lambda could chagne and the payload could change. 

So for now implement this, and then we will see.

**Comment by acidbiscuit** [comment]
@davidgatti 

I am receiving an error in response of `dashboard_app_subscription_check` invocation. `cognito_id` is being sent as payload entry. Please, take a look if everything is working correctly.

```
{
   "errorType":"TypeError",
   "errorMessage":"Cannot read property 'cognito_id' of undefined",
   "trace":[
      "TypeError: Cannot read property 'cognito_id' of undefined",
      "    at /var/task/index.js:33:28",
      "    at new Promise (<anonymous>)",
      "    at Runtime.exports.handler (/var/task/index.js:26:9)",
      "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
   ]
}
```

**Comment by davidgatti** [comment]
It was my problem, I forgot to commit the latest changes.
