### ISSUE TITLE
Load avatar sooner

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#231]
Now when you create an account I do auto generate an unique avatar image, when the site shwos up the first time, the avatar in the top right corner is blank, despite it should be already in S3. Would it be possible to move around the code that loads the avatar in a spot that will make the avatar show up the first time you log in in to your account?

**Comment by acidbiscuit** [comment]
@davidgatti I have some issues with avatars. When new account is created, s3 bucket avatar returns 404 and new avatar upload fails with CORS error. Can you, please, take a look?

**Comment by davidgatti** [comment]
I'm sorry I did chagne the bucket name during a cleanup, this is the right name: `documentreport-production-us-east-1-profile-photo`
