### ISSUE TITLE
Always show header when scrolling

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#260]
if possible

![Screen Shot 2021-03-24 at 3 19 36 PM](https://user-images.githubusercontent.com/411114/112475838-8a893200-8d71-11eb-8cea-8e0d3748a83c.png)

**Comment by acidbiscuit** [comment]
@davidgatti This one is not provided by Vuetify, so we will have to develop it on our own.

In order sticky table header to work we will have to fix table height so scroll happens inside the table, which is completely irrelevant for a table of ~12 max items per page (year). Sticky header is useful for pages with large data sets and usually pagination with per page limit may be more appropriate.

**Comment by davidgatti** [comment]
ok, cool thank you for letting me know, in this case we can skip this one.
