### ISSUE TITLE
Maybe last Avatar image move :D 

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#293]
You might think that I'm a lunatic :D but pleases resist :D

![Screen Shot 2021-04-19 at 1 57 09 PM](https://user-images.githubusercontent.com/411114/115232978-9faa7400-a117-11eb-8e41-9d826f4c898c.png)

**Comment by acidbiscuit** [comment]
@davidgatti 

To clarify:

1) Put avatar as "Identity" menu item icon
2) Change "Identity" menu item to user's name
3) Remove avatar from the toolbar
4) Move user menu as the last item in the toolbar, after notifications button

Not sure what red color markings are though.

**Comment by davidgatti** [comment]
Sorry for the confusion

- red: move the whole menu down, 
- blue: move the avatar in to the menu as the first item
- green: correct
