### ISSUE TITLE
Implement Cognito Sync

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#46]
Cognito has this features called Cognito Sync, where they give you a database where you can store user settings without having to come up with your own Database solution. 

I'd like you to implement this to store UI settings, and for the firs thing would be to store if the menu is collapsed or not. So when the user logs in, on different browser the setting will persist.

Here is the documentation: 

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html

IMPORTANT, if you get any error access, paste it here so I can go an check what I have missed in the Policy.

**Comment by acidbiscuit** [comment]
@davidgatti I've encountered an error when updating the dataset. Reading seems to be working ok. Can you, please, check the Policy?

```
AccessDeniedException: User: arn:aws:sts::257214433955:assumed-role/marketing_merchant_form_cognito_identitypool_authenticated/CognitoIdentityCredentials is not authorized to perform: cognito-sync:UpdateRecords on resource: arn:aws:cognito-sync:us-east-1:257214433955:identitypool/us-east-1:59232971-f16b-436b-bf36-5c65b3bccd0e/identity/us-east-1:26504388-7885-4b56-abf3-70a46d3c2117/dataset/settings_dashboard
```

**Comment by davidgatti** [comment]
@acidbiscuit I did add this action to the policy, if it still dose not work, push the code, tell me how to test this, so I check on the fly what is missing.
