### ISSUE TITLE
Create a DDB record the first time the user created an account and logged in

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#63]
When the user creates an account, and then confirms it, and before you show the dashboard, you have to make a entry in DDB, with the following structure. If possible it be nice if this can happen only when the user first time logs in.

This is important, because when this data gets saved, the whole Stripe pipeline starts.

To test the issues #62, you have to do this first, and then create a new user. 

```
{
  "sub": "62a63e2a-9358-43c3-be3f-9a9e02ab4159",
  "email": "david@example.com",
  "pk": "us-east-1:ecf5ff6c-d920-4cc4-9179-533f203a1424",
  "sk": "user#basic"
}
```

**Comment by acidbiscuit** [comment]
@davidgatti I can think of two ways to achieve described behavior. Need your assistance to find the best suitable one.

1) Create DDB record for every successful registration.   
Pros: easy to hook into, minimal logic added  
Cons: if user is registered outside the app, record should be created outside as well.

2) On every successful login check if DDB record exists and create if it does not.
Pros: works even if account created outside the app, easy to hook into  
Cons: requests to DDB for every successful login

What do you think?

**Comment by davidgatti** [comment]
I will go with option 1, since I'm aware that if we make a mobile app, the app will have to do the same, this is sadly the most clunky part of Cognito.
