### ISSUE TITLE
Nicer error messages?

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#64]
It seams there is no standard for error messages, on some pages there is the snikerbar, that seas there was an error, and in other occasions there is this error:

![Screen Shot 2021-01-03 at 9 33 39 AM](https://user-images.githubusercontent.com/411114/103474704-cd58f080-4da6-11eb-804f-2d20807cbdc2.png)

It be nice to have one standard. And what I'd like to have (free to propose another approach) Show the snikerbar, that there was an error, and then a button that when you click, you can see the full error message with a way to easy copy and paste, the idea is that the error is going to be useful to us when developing, and hopefully the user will never have to see it. But if they do, they get a simplified message first, with extra details if you click on it.

**Comment by acidbiscuit** [comment]
@davidgatti I've added nicer layout for unhandled errors.  
Regarding showing full error messages, I'd like to discuss more conventional solution to keep errors user friendly and get necessary debugging information.

**Comment by davidgatti** [comment]
Sounds good.
