### ISSUE TITLE
A bunch fo Invocie table changes

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#87]
- [ ] new way for query data
- [ ] sort by date, new one at the top
- [ ] if payment failed show when the next retry will happen
- [ ] add icon to copy the ID's on the table
- [ ] format time accordingly to the user locales
- [ ] Display the currency
- [ ] use tags CSS style in the Paid columns, and use green for payed, and red for not
- [ ] click on invoice record, and show a new page with more info

# New way to query for data

I did change how I store the data in DDB, so it is easier to just grab a range, and get only a small subset of data. Now the SK has this `user#invoice#2021#01#14#07#37#33#succeeded`, this means you can query for anything that starts with `user#invoice#2021` and you will get the full year forth of invoices, and then when you do the pagination, you grab the next year, and so on. Of course if you make a query for next year and there is no data, you disable the pagination from moving forward, and display something in the table like `no more data`

# New sorting

Sort by date and the newest invoices at the top.

# Show the next retry

I added a new key in the data, called `next_payment_attempt`, and either it will be null, or have a time stamp, show that.

# Auto copy

Add icons next to all the IDs to click and copy

# Use locales

Display data in the local user country setting, like time format, money etc.

# Display the currency

In the DDB now there is the key representing the currency, display that next to money value.

# Payed column

Use the chips https://vuetifyjs.com/en/components/chips/, to display if the invoice is payed or not.

# New page for invoice details

When you click on a invoice, you go to a new page, where you show all the details of the invoice. Now in the payload I also save the URL to the invoice PDF that stripe provides, we want that also to be on this page.

**Comment by acidbiscuit** [comment]
@davidgatti I can't see any invoices generated. Is there a time delay after payment method has been added?

**Comment by davidgatti** [comment]
I added some fake invoices, I will send you my credentials on a separated channel so you can log in as me and get access to them. In the mean time in your account, you can add a fake Stripe card, and each day you will get a new invoice.
