### ISSUE TITLE
Add raster logo

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#90]

**Comment by davidgatti** [comment]
@acidbiscuit can you propose the best resolutions for the standard and retina resolution?

**Comment by acidbiscuit** [comment]
@davidgatti I can create images from existing SVG versions if you approve.  
Otherwise, here are the dimensions (px):   
- Horizontal logo variant - 240x47, retina - 480x94
- Square logo variant - 47x47, retina 94x94

**Comment by davidgatti** [comment]
OK, please do, this are just place holders anyway.
