### ISSUE TITLE
Collect First and Last name using the stripe widget

### ISSUE THREAD

**Issue by davidgatti** [0x4447-bootstrap/0x4447_bootstrap_dashboard#99]
We need to update the stripe widget to collect the name of the user, and not use our custom form, see if this can be done.

**Comment by acidbiscuit** [comment]
@davidgatti I couldn't find such functionality for stripe widget. Is there any example you can provide?

**Comment by davidgatti** [comment]
Here is an example page: https://stripe.dev/elements-examples/, here is the home page: https://stripe.com/en-it/payments/elements

**Comment by acidbiscuit** [comment]
@davidgatti In those examples Stripe only handles card inputs and the rest are custom form elements and styles. 

We can look for improvements for stripe form styling on the payment page. For example, to match the styles of text fields. Is it something we should look into?

**Comment by davidgatti** [comment]
aaa lame :D Stripe did trick me ;) ok, in this case we will have to redesign the payment page anyway since we need to handle 2 subscription options., so lets finish the rest and we can come back to this one.
